export const school = {
  name: "School of Computer Science",
  address: "123 Main St",
  phoneNumber: "123-456-7890",
  email: "kH5j8@example.com",
  logoUrl: "https://example.com/logo.png",
  active: true,
};

export const teachers = [
  {
    firstName: "Mbidde",
    lastName: "Mukasa",
    email: "9TQ9E@example.com",
    phoneNumber: "123-456-7890",
    dateOfBirth: "1990-01-01",
    gender: "MALE",
    maritalStatus: "SINGLE",
    occupation: "Teacher",
    nationality: "Kenyan",
    addressLine1: "123 Main St",
    addressLine2: "Apt 1",
    city: "Nairobi",
    state: "Nairobi",
    postalCode: "12345",
    country: "Kenya",
    profilePictureUrl: "https://example.com/profile.jpg",
    emergencyContact: "John Doe",
    emergencyPhone: "123-456-7890",
  },
  {
    firstName: "Aisha",
    lastName: "Khamis",
    email: "AK123@example.com",
    phoneNumber: "234-567-8901",
    dateOfBirth: "1985-05-12",
    gender: "FEMALE",
    maritalStatus: "MARRIED",
    occupation: "Teacher",
    nationality: "Kenyan",
    addressLine1: "456 Market St",
    addressLine2: "Apt 2",
    city: "Mombasa",
    state: "Coast",
    postalCode: "54321",
    country: "Kenya",
    profilePictureUrl: "https://example.com/profile2.jpg",
    emergencyContact: "Ali Khamis",
    emergencyPhone: "234-567-8901",
  },
  {
    firstName: "James",
    lastName: "Ochieng",
    email: "JO789@example.com",
    phoneNumber: "345-678-9012",
    dateOfBirth: "1980-03-15",
    gender: "MALE",
    maritalStatus: "SINGLE",
    occupation: "Teacher",
    nationality: "Kenyan",
    addressLine1: "789 Broadway",
    addressLine2: "Suite 3",
    city: "Kisumu",
    state: "Nyanza",
    postalCode: "67890",
    country: "Kenya",
    profilePictureUrl: "https://example.com/profile3.jpg",
    emergencyContact: "Mary Ochieng",
    emergencyPhone: "345-678-9012",
  },
  {
    firstName: "Fatuma",
    lastName: "Hassan",
    email: "FH321@example.com",
    phoneNumber: "456-789-0123",
    dateOfBirth: "1995-07-20",
    gender: "FEMALE",
    maritalStatus: "SINGLE",
    occupation: "Teacher",
    nationality: "Kenyan",
    addressLine1: "123 East Rd",
    addressLine2: "Floor 4",
    city: "Garissa",
    state: "Northeastern",
    postalCode: "78901",
    country: "Kenya",
    profilePictureUrl: "https://example.com/profile4.jpg",
    emergencyContact: "Hassan Ali",
    emergencyPhone: "456-789-0123",
  },
  {
    firstName: "Peter",
    lastName: "Njoroge",
    email: "PN456@example.com",
    phoneNumber: "567-890-1234",
    dateOfBirth: "1988-11-30",
    gender: "MALE",
    maritalStatus: "MARRIED",
    occupation: "Teacher",
    nationality: "Kenyan",
    addressLine1: "567 West Blvd",
    addressLine2: "Apt 5",
    city: "Nakuru",
    state: "Rift Valley",
    postalCode: "89012",
    country: "Kenya",
    profilePictureUrl: "https://example.com/profile5.jpg",
    emergencyContact: "Grace Njoroge",
    emergencyPhone: "567-890-1234",
  },
  {
    firstName: "Rose",
    lastName: "Kamau",
    email: "RK987@example.com",
    phoneNumber: "678-901-2345",
    dateOfBirth: "1992-09-25",
    gender: "FEMALE",
    maritalStatus: "SINGLE",
    occupation: "Teacher",
    nationality: "Kenyan",
    addressLine1: "234 South St",
    addressLine2: "Apt 6",
    city: "Thika",
    state: "Central",
    postalCode: "90123",
    country: "Kenya",
    profilePictureUrl: "https://example.com/profile6.jpg",
    emergencyContact: "Paul Kamau",
    emergencyPhone: "678-901-2345",
  },
  {
    firstName: "John",
    lastName: "Mwangi",
    email: "JM654@example.com",
    phoneNumber: "789-012-3456",
    dateOfBirth: "1983-02-10",
    gender: "MALE",
    maritalStatus: "MARRIED",
    occupation: "Teacher",
    nationality: "Kenyan",
    addressLine1: "345 High St",
    addressLine2: "Suite 7",
    city: "Eldoret",
    state: "Rift Valley",
    postalCode: "01234",
    country: "Kenya",
    profilePictureUrl: "https://example.com/profile7.jpg",
    emergencyContact: "Ann Mwangi",
    emergencyPhone: "789-012-3456",
  },
  {
    firstName: "Lucy",
    lastName: "Odhiambo",
    email: "LO321@example.com",
    phoneNumber: "890-123-4567",
    dateOfBirth: "1991-08-18",
    gender: "FEMALE",
    maritalStatus: "SINGLE",
    occupation: "Teacher",
    nationality: "Kenyan",
    addressLine1: "456 Maple St",
    addressLine2: "Floor 8",
    city: "Kakamega",
    state: "Western",
    postalCode: "23456",
    country: "Kenya",
    profilePictureUrl: "https://example.com/profile8.jpg",
    emergencyContact: "Peter Odhiambo",
    emergencyPhone: "890-123-4567",
  },
  {
    firstName: "Grace",
    lastName: "Mutua",
    email: "GM789@example.com",
    phoneNumber: "901-234-5678",
    dateOfBirth: "1987-04-05",
    gender: "FEMALE",
    maritalStatus: "MARRIED",
    occupation: "Teacher",
    nationality: "Kenyan",
    addressLine1: "678 Cedar Ave",
    addressLine2: "Apt 9",
    city: "Machakos",
    state: "Eastern",
    postalCode: "34567",
    country: "Kenya",
    profilePictureUrl: "https://example.com/profile9.jpg",
    emergencyContact: "Michael Mutua",
    emergencyPhone: "901-234-5678",
  },
  {
    firstName: "David",
    lastName: "Chebet",
    email: "DC456@example.com",
    phoneNumber: "012-345-6789",
    dateOfBirth: "1990-12-22",
    gender: "MALE",
    maritalStatus: "SINGLE",
    occupation: "Teacher",
    nationality: "Kenyan",
    addressLine1: "789 Palm St",
    addressLine2: "Suite 10",
    city: "Kericho",
    state: "Rift Valley",
    postalCode: "45678",
    country: "Kenya",
    profilePictureUrl: "https://example.com/profile10.jpg",
    emergencyContact: "Paul Chebet",
    emergencyPhone: "012-345-6789",
  },
];

export const parents = [
  {
    firstName: "Carlos",
    lastName: "Silva",
    email: "carlos.silva@example.com",
    phoneNumber: "+55 11 91234-5678",
    dateOfBirth: "1980-03-25",
    gender: "MALE",
    maritalStatus: "MARRIED",
    occupation: "Engineer",
    nationality: "Brazilian",
    addressLine1: "Rua das Flores, 123",
    addressLine2: "Apto 45",
    city: "São Paulo",
    state: "SP",
    postalCode: "01000-000",
    country: "Brazil",
    profilePictureUrl: "https://example.com/profile1.jpg",
    emergencyContact: "Ana Silva",
    emergencyPhone: "+55 11 91234-5679",
    active: true,
  },
  {
    firstName: "Fernanda",
    lastName: "Costa",
    email: "fernanda.costa@example.com",
    phoneNumber: "+55 21 92345-6789",
    dateOfBirth: "1985-07-15",
    gender: "FEMALE",
    maritalStatus: "SINGLE",
    occupation: "Teacher",
    nationality: "Brazilian",
    addressLine1: "Avenida Atlântica, 456",
    addressLine2: "Cobertura 12",
    city: "Rio de Janeiro",
    state: "RJ",
    postalCode: "22000-001",
    country: "Brazil",
    profilePictureUrl: "https://example.com/profile2.jpg",
    emergencyContact: "Paulo Costa",
    emergencyPhone: "+55 21 92345-6788",
    active: true,
  },
  {
    firstName: "João",
    lastName: "Pereira",
    email: "joao.pereira@example.com",
    phoneNumber: "+55 31 93456-7890",
    dateOfBirth: "1975-10-10",
    gender: "MALE",
    maritalStatus: "DIVORCED",
    occupation: "Businessman",
    nationality: "Brazilian",
    addressLine1: "Praça da Liberdade, 789",
    addressLine2: "Sala 301",
    city: "Belo Horizonte",
    state: "MG",
    postalCode: "30100-000",
    country: "Brazil",
    profilePictureUrl: "https://example.com/profile3.jpg",
    emergencyContact: "Maria Pereira",
    emergencyPhone: "+55 31 93456-7891",
    active: false,
  },
  {
    firstName: "Mariana",
    lastName: "Oliveira",
    email: "mariana.oliveira@example.com",
    phoneNumber: "+55 51 94567-8901",
    dateOfBirth: "1990-06-22",
    gender: "FEMALE",
    maritalStatus: "MARRIED",
    occupation: "Designer",
    nationality: "Brazilian",
    addressLine1: "Rua dos Andradas, 654",
    addressLine2: "Apto 21",
    city: "Porto Alegre",
    state: "RS",
    postalCode: "90000-000",
    country: "Brazil",
    profilePictureUrl: "https://example.com/profile4.jpg",
    emergencyContact: "Carlos Oliveira",
    emergencyPhone: "+55 51 94567-8902",
    active: true,
  },
  {
    firstName: "Rafael",
    lastName: "Santos",
    email: "rafael.santos@example.com",
    phoneNumber: "+55 61 95678-9012",
    dateOfBirth: "1982-01-30",
    gender: "MALE",
    maritalStatus: "WIDOWED",
    occupation: "Doctor",
    nationality: "Brazilian",
    addressLine1: "Setor Comercial Sul, Qd 2",
    addressLine2: "Bloco A, Sala 502",
    city: "Brasília",
    state: "DF",
    postalCode: "70000-000",
    country: "Brazil",
    profilePictureUrl: "https://example.com/profile5.jpg",
    emergencyContact: "Ana Santos",
    emergencyPhone: "+55 61 95678-9013",
    active: true,
  },
  // Continue adding more parents in the same format as needed
];

export const students = [
  {
    firstName: "John",
    middleName: "David",
    lastName: "Smith",
    email: "john.smith@example.com",
    phoneNumber: "555-123-4567",
    gender: "Male",
    dateOfBirth: "1990-05-15",
    nationality: "American",
    emergencyContact: "Jane Smith",
    emergencyPhone: "555-987-6543",
    active: true,
  },
  {
    firstName: "Alice",
    middleName: "Marie",
    lastName: "Johnson",
    email: "alice.johnson@example.com",
    phoneNumber: "555-555-5555",
    gender: "Female",
    dateOfBirth: "1985-11-20",
    nationality: "Canadian",
    emergencyContact: "Bob Johnson",
    emergencyPhone: "555-111-2222",
    active: false,
  },
  {
    firstName: "Michael",
    middleName: "Anthony",
    lastName: "Williams",
    email: "michael.williams@example.com",
    phoneNumber: "555-123-9876",
    gender: "Male",
    dateOfBirth: "1992-03-10",
    nationality: "British",
    emergencyContact: "Sarah Williams",
    emergencyPhone: "555-444-3333",
    active: true,
  },
  {
    firstName: "Emily",
    middleName: "Grace",
    lastName: "Brown",
    email: "emily.brown@example.com",
    phoneNumber: "555-777-8888",
    gender: "Female",
    dateOfBirth: "1988-09-25",
    nationality: "Australian",
    emergencyContact: "David Brown",
    emergencyPhone: "555-666-7777",
    active: true,
  },
  {
    firstName: "James",
    middleName: "Robert",
    lastName: "Davis",
    email: "james.davis@example.com",
    phoneNumber: "555-222-3333",
    gender: "Male",
    dateOfBirth: "1995-01-05",
    nationality: "American",
    emergencyContact: "Linda Davis",
    emergencyPhone: "555-888-9999",
    active: false,
  },
  {
    firstName: "Olivia",
    middleName: "Rose",
    lastName: "Garcia",
    email: "olivia.garcia@example.com",
    phoneNumber: "555-333-4444",
    gender: "Female",
    dateOfBirth: "1991-07-30",
    nationality: "Mexican",
    emergencyContact: "Carlos Garcia",
    emergencyPhone: "555-000-1111",
    active: true,
  },
  {
    firstName: "Ethan",
    middleName: "William",
    lastName: "Rodriguez",
    email: "ethan.rodriguez@example.com",
    phoneNumber: "555-444-5555",
    gender: "Male",
    dateOfBirth: "1987-04-12",
    nationality: "Spanish",
    emergencyContact: "Maria Rodriguez",
    emergencyPhone: "555-777-9999",
    active: true,
  },
  {
    firstName: "Sophia",
    middleName: "Isabella",
    lastName: "Wilson",
    email: "sophia.wilson@example.com",
    phoneNumber: "555-666-7777",
    gender: "Female",
    dateOfBirth: "1993-12-18",
    nationality: "French",
    emergencyContact: "Pierre Wilson",
    emergencyPhone: "555-222-4444",
    active: false,
  },
  {
    firstName: "Alexander",
    middleName: "Joseph",
    lastName: "Martinez",
    email: "alexander.martinez@example.com",
    phoneNumber: "555-888-9999",
    gender: "Male",
    dateOfBirth: "1989-06-22",
    nationality: "Italian",
    emergencyContact: "Sofia Martinez",
    emergencyPhone: "555-555-0000",
    active: true,
  },
  {
    firstName: "Ava",
    middleName: "Elizabeth",
    lastName: "Anderson",
    email: "ava.anderson@example.com",
    phoneNumber: "555-999-0000",
    gender: "Female",
    dateOfBirth: "1996-02-08",
    nationality: "German",
    emergencyContact: "Hans Anderson",
    emergencyPhone: "555-333-6666",
    active: true,
  },
  {
    firstName: "Daniel",
    middleName: "Christopher",
    lastName: "Taylor",
    email: "daniel.taylor@example.com",
    phoneNumber: "555-000-1111",
    gender: "Male",
    dateOfBirth: "1986-08-15",
    nationality: "Japanese",
    emergencyContact: "Akari Taylor",
    emergencyPhone: "555-888-2222",
    active: false,
  },
  {
    firstName: "Mia",
    middleName: "Charlotte",
    lastName: "Thomas",
    email: "mia.thomas@example.com",
    phoneNumber: "555-111-2222",
    gender: "Female",
    dateOfBirth: "1994-04-29",
    nationality: "Chinese",
    emergencyContact: "Wei Thomas",
    emergencyPhone: "555-111-5555",
    active: true,
  },
  {
    firstName: "Benjamin",
    middleName: "Matthew",
    lastName: "Hernandez",
    email: "benjamin.hernandez@example.com",
    phoneNumber: "555-555-3333",
    gender: "Male",
    dateOfBirth: "1997-10-02",
    nationality: "Brazilian",
    emergencyContact: "Isabela Hernandez",
    emergencyPhone: "555-999-4444",
    active: true,
  },
  {
    firstName: "Charlotte",
    middleName: "Chloe",
    lastName: "Moore",
    email: "charlotte.moore@example.com",
    phoneNumber: "555-777-6666",
    gender: "Female",
    dateOfBirth: "1990-03-18",
    nationality: "Russian",
    emergencyContact: "Natalia Moore",
    emergencyPhone: "555-444-8888",
    active: false,
  },
  {
    firstName: "Henry",
    middleName: "Samuel",
    lastName: "Jackson",
    email: "henry.jackson@example.com",
    phoneNumber: "555-222-9999",
    gender: "Male",
    dateOfBirth: "1988-11-05",
    nationality: "Indian",
    emergencyContact: "Priya Jackson",
    emergencyPhone: "555-666-0000",
    active: true,
  },
];
